// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview AI virtual assistant for fitness and nutrition guidance.
 *
 * - aiVirtualAssistant - A function that handles user questions and provides helpful and motivational guidance.
 * - AiVirtualAssistantInput - The input type for the aiVirtualAssistant function.
 * - AiVirtualAssistantOutput - The return type for the aiVirtualAssistant function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AiVirtualAssistantInputSchema = z.object({
  query: z.string().describe('The user query about fitness, nutrition, or app features.'),
});
export type AiVirtualAssistantInput = z.infer<typeof AiVirtualAssistantInputSchema>;

const AiVirtualAssistantOutputSchema = z.object({
  response: z.string().describe('The AI assistant response to the user query.'),
});
export type AiVirtualAssistantOutput = z.infer<typeof AiVirtualAssistantOutputSchema>;

export async function aiVirtualAssistant(input: AiVirtualAssistantInput): Promise<AiVirtualAssistantOutput> {
  return aiVirtualAssistantFlow(input);
}

const prompt = ai.definePrompt({
  name: 'aiVirtualAssistantPrompt',
  input: {schema: AiVirtualAssistantInputSchema},
  output: {schema: AiVirtualAssistantOutputSchema},
  prompt: `You are a friendly, motivational, and professional AI assistant for a fitness and nutrition app.

  Your goal is to provide helpful and informative guidance to users regarding their fitness, nutrition, and app features.

  Respond to the following user query:
  {{query}}`,
});

const aiVirtualAssistantFlow = ai.defineFlow(
  {
    name: 'aiVirtualAssistantFlow',
    inputSchema: AiVirtualAssistantInputSchema,
    outputSchema: AiVirtualAssistantOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
