// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview This file defines a Genkit flow for generating personalized weekly meal suggestions based on user dietary restrictions and preferences.
 *
 * - generateMealSuggestions - A function that takes user preferences and generates meal suggestions.
 * - GenerateMealSuggestionsInput - The input type for the generateMealSuggestions function.
 * - GenerateMealSuggestionsOutput - The return type for the generateMealSuggestions function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateMealSuggestionsInputSchema = z.object({
  objective: z.string().describe('The user\u0027s fitness objective (e.g., weight loss, muscle gain).'),
  dietaryRestrictions: z.string().describe('Any dietary restrictions or allergies (e.g., gluten-free, vegetarian).'),
  preferences: z.string().describe('The user\u0027s food preferences (e.g., favorite cuisines, preferred foods).'),
  weeklyAvailability: z.string().describe('The user\u0027s weekly availability for meal preparation.'),
});

export type GenerateMealSuggestionsInput = z.infer<typeof GenerateMealSuggestionsInputSchema>;

const GenerateMealSuggestionsOutputSchema = z.object({
  weeklyMealSuggestions: z.string().describe('A detailed weekly meal plan with specific recipes and instructions.'),
  macronutrientDistribution: z
    .string() // Changed from z.object to z.string()
    .describe('The distribution of macronutrients (protein, carbs, fats) for each meal.'),
  shoppingList: z.string().describe('A shopping list of ingredients needed for the weekly meal plan.'),
});

export type GenerateMealSuggestionsOutput = z.infer<typeof GenerateMealSuggestionsOutputSchema>;

export async function generateMealSuggestions(
  input: GenerateMealSuggestionsInput
): Promise<GenerateMealSuggestionsOutput> {
  return generateMealSuggestionsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateMealSuggestionsPrompt',
  input: {schema: GenerateMealSuggestionsInputSchema},
  output: {schema: GenerateMealSuggestionsOutputSchema},
  prompt: `You are a personal nutrition assistant.

Based on the user's input, generate a personalized weekly meal plan.

Consider the user's objective, dietary restrictions, preferences, and weekly availability.

Objective: {{{objective}}}
Dietary Restrictions: {{{dietaryRestrictions}}}
Preferences: {{{preferences}}}
Weekly Availability: {{{weeklyAvailability}}}

Generate a detailed weekly meal plan with specific recipes and instructions, including the macronutrient distribution for each meal and a shopping list.`,
});

const generateMealSuggestionsFlow = ai.defineFlow(
  {
    name: 'generateMealSuggestionsFlow',
    inputSchema: GenerateMealSuggestionsInputSchema,
    outputSchema: GenerateMealSuggestionsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
