// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview This file defines a Genkit flow for generating personalized weekly meal suggestions based on user dietary restrictions and preferences.
 *
 * - generateMealSuggestions - A function that takes user preferences and generates meal suggestions.
 * - GenerateMealSuggestionsInput - The input type for the generateMealSuggestions function.
 * - GenerateMealSuggestionsOutput - The return type for the generateMealSuggestions function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateMealSuggestionsInputSchema = z.object({
  objective: z.string().describe('The user\u0027s fitness objective (e.g., weight loss, muscle gain).'),
  dietaryRestrictions: z.string().describe('Any dietary restrictions or allergies (e.g., gluten-free, vegetarian).'),
  preferences: z.string().describe('The user\u0027s food preferences (e.g., favorite cuisines, preferred foods).'),
  weeklyAvailability: z.string().describe('The user\u0027s weekly availability for meal preparation.'),
});

export type GenerateMealSuggestionsInput = z.infer<typeof GenerateMealSuggestionsInputSchema>;

const GenerateMealSuggestionsOutputSchema = z.object({
  weeklyMealSuggestions: z.string().describe('A detailed weekly meal plan with specific recipes and instructions.'),
  macronutrientDistribution: z
    .string() // Changed from z.object to z.string()
    .describe('The distribution of macronutrients (protein, carbs, fats) for each meal.'),
  shoppingList: z.string().describe('A shopping list of ingredients needed for the weekly meal plan.'),
});

export type GenerateMealSuggestionsOutput = z.infer<typeof GenerateMealSuggestionsOutputSchema>;

export async function generateMealSuggestions(
  input: GenerateMealSuggestionsInput
): Promise<GenerateMealSuggestionsOutput> {
  return generateMealSuggestionsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateMealSuggestionsPrompt',
  input: {schema: GenerateMealSuggestionsInputSchema},
  output: {schema: GenerateMealSuggestionsOutputSchema},
  prompt: `You are a bilingual (pt-BR) nutrition coach.

Retorne um JSON ESTRITO que corresponda exatamente ao schema de saída e escreva TODO o conteúdo em Português (Brasil).

Regras de formatação:
- weeklyMealSuggestions: organize por dias da semana (Segunda a Domingo), cada dia com seções "Café da manhã", "Almoço", "Jantar" e "Lanches". Use listas com bullet points; inclua porções aproximadas e breve modo de preparo quando útil.
- macronutrientDistribution: traga um resumo diário com kcal aproximadas e distribuição de macronutrientes (proteínas, carboidratos, gorduras) e observações rápidas.
- shoppingList: liste itens agrupados por categorias (Proteínas, Carboidratos, Hortifruti, Laticínios, Outros), um item por linha.

Contexto do usuário:
- Objetivo: {{{objective}}}
- Restrições alimentares: {{{dietaryRestrictions}}}
- Preferências: {{{preferences}}}
- Disponibilidade semanal: {{{weeklyAvailability}}}

Produza textos curtos, claros e práticos, sempre em pt-BR.`,
});

const generateMealSuggestionsFlow = ai.defineFlow(
  {
    name: 'generateMealSuggestionsFlow',
    inputSchema: GenerateMealSuggestionsInputSchema,
    outputSchema: GenerateMealSuggestionsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
